### ISSUE TITLE
Docker image not reading environment variables

### ISSUE THREAD

**Issue by MrSuttonmann** [kvnallsn/guacamole-jwt-auth#18]
Hi,

I've tried to deploy this today, I'm using the pre-built docker image and have set up the environment variables as per the instructions.
```
services:
  guacd:
    image: guacamole/guacd:1.5.3
    restart: always
  postgres:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      POSTGRES_DB: guacd
      POSTGRES_USER: guacd
      POSTGRES_PASSWORD: password
  guacamole:
    image: ghcr.io/kvnallsn/guacamole-jwt-auth:latest
    restart: always
    environment:
      - POSTGRESQL_DATABASE=guacd
      - POSTGRESQL_USER=guacd
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_AUTO_CREATE_ACCOUNTS=true
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - JWT_HEADER=Cf-Access-Jwt-Assertion
      - JWT_JWKS_URL=https://REDACTED.cloudflareaccess.com/cdn-cgi/access/certs
      - JWT_JWKS_PATH=/keys
      - JWT_AUDIENCE=REDACTED
    ports:
      - 8700:8080
networks: {}
```

Unfortunately when running, I get the following error:

```
guacamole-guacamole-1  | FATAL: Missing required environment variables
guacamole-guacamole-1  | -----------------------------------------------------------------------------------
guacamole-guacamole-1  | If using the JWT authentication extension, you must provide JWT_HEADER or JWT_COOKIE.
guacamole-guacamole-1  | If both are provided, JWT_HEADER will take precedence over JWT_COOKIE.
guacamole-guacamole-1  | 
guacamole-guacamole-1  |     JWT_HEADER          The name of the header storing the JWT
guacamole-guacamole-1  | 
guacamole-guacamole-1  |     JWT_COOKIE          The name of the HTTP cookie storing the JWT
guacamole-guacamole-1  | 
guacamole-guacamole-1  | Additionally, you must also provide the following environment variables in all cases:
guacamole-guacamole-1  | 
guacamole-guacamole-1  |     JWT_JWKS_URL        The URL to download the JSON Web Keys from
guacamole-guacamole-1  | 
guacamole-guacamole-1  |     JWT_AUDIENCE        The value of the 'aud' claim in the JWT 
guacamole-guacamole-1 exited with code 1
```
